#include <chrono>

#include <bit>
#include <cassert>
#include <cstdint>
#include <fstream>
#include <string>
#include <string_view>

uint64_t priority(char c) {
  return 1ul << ((c < 'a') ? (c - 'A' + 27) : (c - 'a' + 1));
}
uint64_t priority2(char c) {
    int isLC = c & ('a' - 'A');
    int sh = (c - 'A');
    sh += isLC ? (1 - ('a' - 'A')) : 27;

    return 1ul << sh;
}


const char* inp = "fzmmmfwDWFzlQQqjCQjDGnqq"
"tJHJvLJVVttNsvTtTvgHHSVwCsQRQQZCZZMqQMQBnqBMQs"
"LgThNJhNSgTJVgvgtghPhbpfWzfbwfPmpprb"
"lDLnSnLZRjmWrlhrFF"
"PffQJNqJbPZbpmjrrCVNFmCh"
"qzbcbqfMfZMTfQTqqzzTPPLMHgBBBtHRStvgHRDBnSRL"
"WPZfJlZZCMwwZPWCwWzVHQhsshVSsfNQHdvQNN"
"FLGDGGnGdVjQQQDQ"
"ccFFbggLnRcLFRtFBmnJzdZZzZBMpwJlZMppMp"
"RZsnCZssCnDccJCnfcQfHTdzMzhdLdMTqdRqpRLwqq"
"tNrGNrrvGhTThQqw"
"rrFStPgrFWWgvmPgQjtmNtmJcfJcsJsZblDZfbfHDFHnfl"
"RdTfgbbPbJWDDqRvsDsmVG"
"NSQZLQZHpFGLqnLszrJm"
"ZMSNMHhNZMMSQwhQJWPBJCbhbcgtgfcJ"
"qZfqPvLnnZGpGpCJlvsMsMlHJJHB"
"mTWFFFTTtVSJMzzjWgSH"
"RbVdtdFtcrmbRQDDVHDQTbDNwLPLfnqZnhZhQnNwfNqnnn"
"nhHfSGHGThhZjnhrrSnsSczdzlfzzdQQVzRNFNcFdl"
"JJvCDvmCbtvpvbMmDvLbCJpmqdVVVcMcNGzRcNFcRRzRclQd"
"vwDCwtLmwLBDJmCHHjHHWGZHBnsnnj"
"QWTMqZhThbTbLwtGBrQfQQNr"
"jdzSSccVPPcgcLrDBtDVwCfNNC"
"vcBgcmssccplTnnTqsMhWW"
"FlcwZhBhGZhFJnGtZZFwlGsWRLHdWqMzPjWRLTLJHHjdWq"
"vfmrmbpfpMfzjHjfdM"
"VCSmVpmrNDMZhSMcsFnh"
"nHqQVtVZGGwwwnSF"
"fMBBBWCsCfMMbWfbsGmGzFjQGQFCPhFQhF"
"fbcsWpJRsWlcNVLtqtLLQcZQ"
"rgNJdfNJpgpJVMMVfmfVJgCtCTqqqzwTqrBsTswcCCss"
"lFLHGWLvHQFhnQFhbFnbHWWPBtwqzBPTcsPTswZCPBGCTC"
"QQtbRtLhtjgdfMRMDV"
"jTRhJpGhQPfPLsDhWh"
"wVVMbqbHwVwwMplHWfsfNmWcSLqcLmSs"
"lVCZlHnwHdRpRGvZTBGJ"
"csppppDDbGLbSqndFHHNdHsH"
"lVTlgWgjzCzfgvfggZWWlnHPPBHrSCqBmrSBrHHBnF"
"QFgvFfjTvZjzlvVTWljvTtMbLcccbRRMbwLMMLQLbw"
"tjhLjLJzpJpwjsqqfQqNrNfRnsRR"
"WvwGBPwWZZrnbBNrNnnC"
"PDvGVTgvTMGvZTGTPvWDZVJjljtLzhtmLlJjwJVJLm"
"WbzpSNswNWszwSLgSNMcrrBfPJJcfsHMrvMv"
"CFllhlGFDVFRCmhQDlDTBBcvgBCTcHPHrfrHTJ"
"qGRgVFhDDZmDnDqhgQFGqzwtzSjddwZbzwpLNzjpdS"
"FlpZrQSJJmQpSpqlQgbbRZCgGCZdDdbNdd"
"WswHfjfnhWPFDsFRDcbBbR"
"WjHvjjWTfTvHFjzvPnPtttVTTJVLtJSpmtlltp"
"tnjrnnnnhNlPBtbbcWpZScpjbZSz"
"wmsFqfqqqGHTLbzpLLbgzMcH"
"FGJqsmQGRVFwwQJschPdhPrBndBhtPhrQQ"
"dRdJRfTnCRNlJjPBDmBJsbBDzm"
"wSFWSgGVSLwpFhpLhQjzgPzbtDPDbPBsztrP"
"WMGvVMLLBCclNHHRlM"
"gfSffQBDBtZvwwpWDHcbwb"
"JnCmmJCRmztsVPJRFjFchcGGWFWcGcHFvGLvHF"
"VCPzJnsPVCjtPjdMsMdmVmMBfgTZBTMfSfZSSlfNNgSSfg"
"lwHJSVZHWWVwJQwbbVVtwWVVdpdPfRfgDLPZLTZLDLgRDTZL"
"hhBrBqRcnhsFFfddmdmmCmmppn"
"MNNBBRRshNHbtVMzQJMM"
"NBsSNtLNTtNsvlTBBRLgFSCbFmbHFCFhgcghSm"
"WJWWDdVzDZJjDJQcCDHmmhCnmHmHFm"
"zQVdQZQwqVQHjqzWWWdHpzMwGMBlGLLtTvRvRNsMwwNN"
"ZCztttSjGSqRZgRPDNQQNr"
"hLvmHshLmLcFwwhhwLqMVRRRJQQVNnRJMVRDNNRr"
"HFhTpFqqLcssmqmFftblBSjCjStjbGWBfj"
"crffjHDfrQfnfpLPgbgP"
"TmFvFCmFTFFCtNsmMsRvlRTpPbLGMnGSngPppShGpbdgGJ"
"vmslmwTNmtstzFsCvRFrHBrDZzcQnWqcDDHqQB"
"LQLPVLGdGrRPRhHgwMhllhhs"
"ZbSZTNqSZfNqNCtSSmTttbpSWMlzWlslpWHsWgJWhwJzBMlz"
"bqjqqFFjHqTTTZTmSNbfmdrFQnDdcvVDGQDvvVnQnr"
"mQdcdsSThlccSWhMgDnQnFtjQPtnjPNvtR"
"zzsGwzrrHGBfZJGrJpDtNHFjvNvDvVRvNRtV"
"wZBCGrbrszTbThcTcLcb"
"gJDDDDcPQgQfNFPhhZGDDcZZSLVtlCqzsMlzqpszlsVtFSql"
"bBrdwHTrHWTrTtzLlSMCCCprCq"
"dnBwRvmnbmBvTpbnbWbTjZPQJhhchmJcmcQPfmGNcJ"
"sjMGBLWGZjsLjJTBCCbvNrBCHC"
"mpcRfDSSdqDdlRqdwRvFrHFbrHJFJVvDVrTb"
"qvlgqwpcSQSfLjjhzgnMzsnP"
"VgmLHHNRNVLNhsNgRHLltjjbCWnCWZbldntW"
"GGMFPJqPwJGTvvCCdqdqlqCj"
"rGwGrMQzJQBjJwTVHgDQDHcsfhVhVg"
"pblwGBlFlWwwlgCSFwbLvQZFvzvZhzvmQTLLzJ"
"HfqccHzVDNqLmmPmPPQZ"
"MNtrVdDjHtrzGBdbGWCblw"
"NNhnnLdnnfhdhVjvThvqVvCj"
"tHtHBzBGWHBWGtPBSvvpGZVbSsTFjSqqVbscgjCjqqSC"
"HBtzJHzzpDZpzMWpGPtWHvZwQmNLlmQnmNdfMmNRmwmlwd"
"QzGqGwmbfTdPBgRRcgmMPC"
"NtNZhljrNjrSrtltWlCJCJJfcVVRcJcRgPjf"
"NlWSZZWsHhWWlprSSvZWHrWfQLLQbLGfQpQzzTFQbwzQdd"
"gcwcSnccnwLRRSzcBQRvZZdvtNtvRbQJQv"
"CqrCrrPsVstvbfDfbb"
"TPlPVhWFFMGMnMjbcT"
"gjjHGvcHgsgbSRQbRFWbjC"
"ttnBTNSSfwBLzplWPPdlLlMPlMCQ"
"TBZpDtmnnZNvhJDHggqqgS"
"zfqzzGwMbllcJFqm"
"NpHgpRZrRpSrSZLghlTjchNlNbhFmchb"
"RHLWHgLBggZpHpgHRZrLgZLQCMzCfDWGMCzMQQGvPmvvfC"
"bBWWlFFBBFdVMLfvsfjrtBvTrr"
"qZsgNZzcwfjZrfPf"
"gcnNNcDncsDGzggDnNRJnzHhmlMVSSbhVVVmMbbhVmMlGl"
"dNNRQszqRhPNfddWltvDltMMNlnncv"
"ZjZbpgpSpjpJgpCCpbFlTnSDTlzclDnMvnnMlT"
"GCJpjbgzJCpwZwrHZrgHsRBwBVRRsqdqPhLBQqsP"
"mnnVCcwGwnsVJntmfnBtBhTDzpzzpDWbDbsLLzpWDz"
"FcHQdZSRHbhZZWWhrW"
"dNljMlPPHdMPvRlHMRdjRRNBnwJfCVqwqqffCfCwtcBV"
"ZGtGzBBGjvdZvLWLcrPVcZcsNVNmVpcH"
"MnlgngCJMgJbhfDbCDPrHHVcNNrVpbVpVmmcVq"
"lSPhlClftSSBvdGS"
"jFhGqVCcPMMdGFqczBltzrtglrsrjBgB"
"wWgwvfDZvnpmnHwHTfNpDbtRWbzltRlSrRlbBSbbzt"
"fHJvJvvTwwJPhCccgQCM"
"BrrrBVgNppDVBbTgDvqWdWZqWqwNmNNHvH"
"sHsHnHlcJjFwMMFFvGdPvv"
"HllCQCJQJsnjgtVTbBgpQrSr"
"JgLPLwbhBrCbLBCJPFFlPFZRTNTZFRqlRq"
"pmffSWvDcfSfGmvsNHZsTRsWllssbT"
"vDddMmScdStfzGcpzzwhJwJwnCbLwwLLCwht"
"sWSSvmsZsdZPWdLPRRsmSrrnlnvJjfnggfrgtfjnjr"
"VWWWBhhHBBHtljMMfJHrrt"
"WWqpWVqQqLNGRNZP"
"QHjjGVBQpffpjqppQsSsQHWJcVVgJFWcFTWgNLggFPNc"
"bzzmbzzZnZztFTNJWRqmqcgJ"
"zDZlqMtbwhCBBfppvHDGvf"
"BNTdfWJmzHNHHzzTdLCfCfCswQjRjljVsh"
"FbGnrFnrPGSSvGPFZFFPGClLQpjQRwLjLplQhRlsrQ"
"GbnvvgvPFwbwcnZMMGSFvFHdNHmTBNJNmmmDTJDBmWcT"
"rBhRPrjJrRtTHtWHWcjc"
"SDdGqmhdFSqblLGlHHfHWl"
"DSSmFqhsFqFdzqFgwsVnvBQPPQPQVrnRsJMR"
"NZcgQdmSwZgdPFPVNFPqqVVF"
"hlhhjMhGjLhLDGDhCBJDCrRFRrqqpLPfpfPRVPprPm"
"MlhjlMDDJTCmZddQQSTcTT"
"zRddrwzwNhrzrtCLtLfsLrqflC"
"MbSDZvVwGZpJwvHvBVfsqtjqlsPPfsqsfclb"
"vJpvJvZTVgTdTgwdTn"
"SZMsTTScDMqwtDDJ"
"VWrbzFvnrvFQQtnhzdPFmfwGfqmGPfDwmfPJ"
"rrLbrnVrLvVQpLHSHjsTBBjZBt"
"bSrpbWpPpfzPRWrWvhJgddrcccgFnFss"
"ljGNTCtMNLGQjNMjQMGtZJDDggcldcFcvhdFddnhhF"
"vNCmQMjmvGzpRPPzzmfw"
"BrbdcqcdSZRLQltNDqFpCpHH"
"jnTzWsWjWjwTQnzMvFlCzNDhNhDCFGpHpH"
"wmmvjVQMvwmsQMMwnsTPgVfgJcLcgfSbbBdBbJSdbSBS"
"bJFbMdcmgFSFgmggJFcGwjRdzPWZWGDDGGRwGD"
"hrttffCVVCTVlrttQwzRzwWTqRGDGwjTvG"
"rfLChHhlpHrfHlnWlpWCpQVcMSmMmSJMmggbmMSMLFNSSs"
"JRMBJfMJQJTcNNdD"
"LHsLmspghmmpdwwwcwRCpPTT"
"ttLLlRSlqjrMqFtZ"
"VjtHVHtvVqttCdnGpHtplcshglNgprrlMhrcNghw"
"WTWRvRWFZQLWDvDWzwscNfcflcshlshFlw"
"WQmBQWPTVGnJPnvn"
"cpRwjcQwVfQzQPQl"
"BZgGDBZBsgWBDDJzlhfhJVmzVfmThm"
"FqWDDGrGDFNqFrDZFnplNHnSwtnSRwRplN"
"VMLVRhRLRfhfgGdfVdZWRdTHNqHCDTrSJNBBBgJNQgND"
"swlcpsFPcPwzpSlTTDrNrQPQqQBBrH"
"zsppFscsscmbzsFsbsZbMfRZdVdVMbVSWhLG"
"NjcjHFjrHHFpjGtVtGWVZW"
"fwPlsJqdndPnwJfQdfllwNtWGdtWMMbtbmbGWbMWGN"
"CPlwnCwnwqClTJThTDzzFcHNSShrRh"
"llqlsNsPNTpDNTDNNf"
"cnvcWFjSrMSFnvWHTzTggHCcllzLpg"
"wjJSSrFrrMMJGrFFFGjGvJnFswsRwRdmBdZbbqqsPtQqPZls"
"jlclpqjcRqpjzjnVPgTmBmjCrC"
"vGvsFNGGMZNvdGshQNJvJgbVMrnbrHVBgBTTbBBPBT"
"SvJNGhvvvFdfQvFshSpqRRPctRcLWwlf"
"""LWSSqLVBbNqqLrWHLSHzQfFgZtmtJCQZzgtCFCQCCnJQ"
"PlldGDGdjGsMPhssjFJghChZQJgv"
"jwMcMpsPRRdsRjPwNLSTNJWT"
"hWnMWgTffWFbMLfHnHgNRzjBBSzSBBcStdzBtz"
"VGrVCGcVJswvPqJQjBzjpt"
"ZqqsCrmmsfmWcH"
"vnNnssMcZnlnlMFMsMGLbNLNqgLbgLNTCpLgwC"
"hmjzBzHmRSfBfmqgQJbT"
"WVVtthRtRdsdqt"
"LhZBLfZpmcsF"
"vTRRwTRRPnCTwlFgmLms"
"HVVVNCPPHTTtClRVNTHMMHrHWBhrQbJhWMMbZbJZ"
"WPTnnDPjvPlChhJP"
"DRQdBqsDQHQLHsBSmbwbgCGlJghgmhgw"
"dHMHQDVVRBsMWTNfW"
"PlgFPFFJGgJhhMGZwtQtBttptlSb"
"TTcDzmHvdvnDDzdTVSsQLpWmSsmqppsWtb"
"CHVdcHvdbrwJCMPR"
"BtBfcPfBhBGDhwHMl"
"dQdzLFTQnRnQVvgLnCpNrHJrwm"
"zRVLZQRRvQGbwtWf"
"PPcWcwMmCwwgnphCC"
"TtZsJTzzJSSSZJsdJblHHMngpLnnjHps"
"ZDrvdFZtJqtStrZfMwfWmP"
"wCwSzzsHChhMVMhCPFWGPccRdjFdJjDR"
"wBTTlBfgTlfpQQltmctJJFDJDDWdDt"
"TppwnmlnQQqnlpqlmppVrZZSzshzShqzsrZVqs"
"CCqCTgmdMCCCMMsWgCmcGGJfrGNGrSrrQpwFFSwG"
"vZbDZvhDbzHzwNzwN"
"ZjBRVHPRtRLjLMWsCM"
"MMsstRChwbChqRBqDNDNlJdr"
"vLmPLfGGGGcTmFfTSvpHZpdrFJplQdZHQdHH"
"GgPLmvGVSPfmfcfgBRwtVWbh"
"LPPgFPccLPRswfsHf"
"bpbpTnCCrnmCtjBnTHDwsDhQ"
"BbrjnjnWCbBWZbPWzWdS"
"pnncvLbcppBHgBRp"
"MtJfjVMtMmFJDjWSjdGBzBGNBMCGNB"
"ZdDdsJFdDmtJmLTbwc"
"FGsfFdNdhfbDdbhbLNTCZTLJnCRVJLPCRTVR"
"qHjsczptHpmgHZBBVP"
"lmpSlcglQtqWtcWjpsGFwdbGGNWhDv"
"hNNNjMFMwthjFfvZBNSGGdGmHzHgGWSfHWSR"
"ppJpcCVslpQJpJJDWRHSDn"
"QbsrJQTQJVJNMNnZT"
"NmRNLtGNmfcRrtDtr"
"blSzzSBssgfslWCCCH"
"zTzbPBhMlTVSzMlMlvvGcQRmqLLfvRwQ"
"nnZsfsPLLfZfHLWdsdmcGmNScJTRGsTJmNcF"
"gqVqDMgBlDbwwCqVbNFJNSrqqTSm"
"jlMVMjljQBjMwhLfWfhH"
"bfHwMvzwFBNp"
"nddcVJpGVpGqPVBBFhms"
"DWcPgPcPgnqCPlWWVbzSLbvgLpHHMz"
"NMVqtdPVHgVlrfVrpNjNNpCb"
"zhSvfWWzRfRLfvSpQmmwCD"
"LBRRTRcLJSgqqMJl"
"GpgNzzSMGpGTrgzgMPgBdBlBbLRBjdBwVbLRVbSR"
"sQWCfQcflhtQQcWCmbLqqBmmbBVbLVLwnB"
"fCtQWFWDZFCQhCctFNpZJpgJJNTgNlPZgH"
"DqLtMSDLLttjdDSRdpdslFWrqWPqhwhfFwwCFw"
"CvTbNvvTJNGHnVJwPF"
"cQBzGBHnTQGgcNtdMBtL"
"QsNDfdDNQsSTtrQZQ"
"lLvRWMVMLzWbRjvVgmTBrTFFbmJCmsBCrr"
"lljvlgpMGgRpsjsRldqqNqfhqqSdncpqdP"
"sVSJVmmtmsCCwschr"
"ZgLLfqvzzqgfdqHQLQQrhbNGBwgGbMlNcFclwN"
"LTzqZrHHQvjLHnHdQvZpCJDPmCRRtCpStRRmVtmm"
"ccQVcVHwnnDqNqSWNwcgRslgmdGlssmGbQdddb"
"rpFtPrzrMFZvZTLPpsssJhsggG"
"pTtLtBMjZLfHvNWq"
"PZnSjnnsVfjf"
"crvccpglrtHfNbzbH"
"lptTLFFpdgvttFWltlDSMPhJPhChShPBZBMJhPMT"
"mPSPdnhznPdhSmPGcDtgFgWpFBQhTBMg"
"rHNNvbqHHHwZwMGMWM"
"wRqqRffvvNHwrHqrNrqzdsGJsSsSdSsLPVVPnjsn"
"CzlngWpClJlzRJpDnndrhwcsBcLsNcsmLdQQ"
"qqSjqFGTFbPFSPTVjsDBVLrNcc"
"PtDDtZTvGDvFCMzZl"
"vtQDpvpvVvvcSFrrlV"
"RqcTTRddRrlsjZ"
"zmbdRdMmMgbPDcGhG"
"gZqJRZRZdltFVGZQ"
"MCMSRHCMRHBBVtVCG"
"jcHsTMBNSSrBMjmMrRqllnprqzRPzdlP"
"mWSWHdmHWZWj"
"TvchwtTfcTvhzwVGNjnnNr"
"JTdwghvMzwfdcMVJqRPRJFFC"
"DsHDCrszvvhHsshvswdFgWLpbRpWFfMjWjWF"
"BVJPJmPmGZVnfbVfM"
"cNGtnttqmJHNvNzD"
"gpjmMQMrfmMntCSCN"
"vDRqphDhzHSdtq"
"LFLLcbJRJLppFQlp"
"SnSdvchzZZczndNvwrGTfhhTDgRGGLQQ"
"lVWHWMmWmttsFBMLLRRGTf"
"bsFPbFFssmFjWRmjVczwvwZccndpvzpzCP"
"jzngbHrlHQllcbcTCtfqWC"
"JJgmsJRwFqChLG"
"SmJmSmDdSPRwSMppJVvvjrNMNjMZZrQgZNgQ"
"PvPlPcZPZFllzNzCDHjjHBHB"
"VmgWtJWrqbQmqGDBdh"
"tmbgggbgnMWnStttgzrFnccnPclT"
"RQQbdSRdpprQSNVqqfjJnhnVvHhBhVjJtjJz"
"WGgGgLmLgGZMPDBhDM"
"WPPwPGwlLgZwmWlslbrRrNNQqsspBT"
"dNNpHpchLppdccTNtRPPPSbSnhhrhnSJ"
"qfqsFsqffgQMznJrP"
"vglfqQCgDgFjglCDCTHtdcZVVN"
"FWtDHDStZwrFCDwrgsWlMdpZzlNpNjdjjQzNzj"
"BqnVGVcbTmGfHLGVzvJlMdJp"
"ThRRchnHqLTGbFCCCF"
"wJrwdZPnJwqPbJPCnvHLsTsDtHsHDDqvpH"
"RWzNRWjRfgjNMMLvc"
"WGGRQzzRmRmVQSgwrCbShJ"
"cjngcvcwbMwWnbMWjsjqfthqsBtsJJJJBt"
"HrGFmDDzpmLTHpDsPBPPqN"
"DDVmDplDrpGSVSTTHnPWcvWCdPbbMvcVdW"
"BVRlBfPBffWswVWQsNPmGFZGnWZGtztrzMZMnz"
"HqSJchHTHbTgHhGhvmnF"
"RJqHTpgDLJDSqLJJPfPVLlfN"
"NDrBlSmrFBlbbJllmhNtqHVRzQ"
"CMTCGLcvvtfCdCcCvMcwVZVRLjRRjQjRHRwzwjVH"
"dfGdgGMGPggnvfvgbSJJPslJ";

uint64_t BM_p1() {
  uint64_t res = 0;
  int i = 0;
  while (inp[++i]) {
    res += priority(inp[i]);
    // res += priority2(inp[i]);
  }
  return res;
}

uint64_t BM_p2() {
  uint64_t res = 0;
  int i = 0;
  while (inp[++i]) {
    // res += priority(inp[i]);
    res += priority2(inp[i]);
  }
  return res;
}

int main(int argc, char** argv) {
  static constexpr int loopCount = 10000;
  uint64_t sum = 0;
  auto t0 = std::chrono::steady_clock::now();
  for (int i = 0; i < loopCount; i++)
    sum += BM_p1();

  auto t1 = std::chrono::steady_clock::now();
  for (int i = 0; i < loopCount; i++)
    sum -= BM_p2();
  auto t2 = std::chrono::steady_clock::now();

  std::chrono::duration<double> p1_t = t1 - t0;
  std::chrono::duration<double> p2_t = t2 - t1;
  // sum should be 0 at the end here
  printf("day3 bench: priority: %f priority(branchless): %f sum:%lu\n", p1_t.count(), p2_t.count(), sum);
}
